export const blogPosts = [
  {
    id: 1,
    category: "Shooter",
    dateCreate: "2025-02-21",
    title: "The Rise of Tactical Shooters",
    shortDescription:
      "Explore the evolution and impact of tactical shooters in the gaming industry.",
    author: "John Doe",
    comments: 12,
    minutesToRead: 5,
    views: 1532,
    featured: false,
  },
  {
    id: 2,
    category: "Adventure",
    dateCreate: "2025-02-20",
    title: "Epic Adventures Await",
    shortDescription:
      "Join us as we dive into the best adventure games of the decade.",
    author: "Jane Smith",
    comments: 25,
    minutesToRead: 7,
    views: 1894,
    featured: false,
  },
  {
    id: 3,
    category: "RPG",
    dateCreate: "2025-02-18",
    title: "The Future of RPG Games",
    shortDescription:
      "How the RPG genre is evolving with technology and storytelling.How the RPG genre is evolving with technology and storytelling.",
    author: "Alex Johnson",
    comments: 30,
    minutesToRead: 6,
    views: 2023,
    featured: true,
  },
  {
    id: 4,
    category: "Battle Royale",
    dateCreate: "2025-02-15",
    title: "Battle Royale Games: A Global Phenomenon",
    shortDescription:
      "An in-depth look at the massive rise of battle royale games.",
    author: "Chris Lee",
    comments: 18,
    minutesToRead: 8,
    views: 1325,
    featured: false,
  },
  {
    id: 5,
    category: "Strategy",
    dateCreate: "2025-02-10",
    title: "Mastering Strategy Games",
    shortDescription: "The key tactics you need to dominate in strategy games.",
    author: "Emily Taylor",
    comments: 10,
    minutesToRead: 4,
    views: 1021,
    featured: false,
  },
  {
    id: 6,
    category: "Sports",
    dateCreate: "2025-02-05",
    title: "Top Sports Games of 2025",
    shortDescription:
      "A roundup of the most anticipated sports games this year.",
    author: "Michael Scott",
    comments: 8,
    minutesToRead: 5,
    views: 1345,
    featured: false,
  },
];

export default blogPosts;
